# Permalinks
permalink:            pretty

# Setup
title:                "#digitarhythm"
description:          "Video games music playlist."
url:                  https://lukafaxx.github.io/digitarhythm/
baseurl:              /digitarhythm
exclude:              ["Gemfile", "Gemfile.lock", "LICENSE.md", "README.md"]
sass:
    style: compressed
