# Permalinks
permalink:            pretty
relative_permalinks:  false

# Setup
title:                "#digitarhythm"
description:
url:                  http://lukafaxx.github.io/digitarhythm/
baseurl:              /digitarhythm
